
name: hello-world


on:
  schedule:
    - cron: '0 12 * * *' # runs at 12:00 UTC everyday

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    
    environment:
      name: test

    steps:
      - name: checkout repo content
        uses: actions/checkout@v3
      
      - name: setup python 
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.8'
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: run hello_world.py
        env:
          CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_SECRET: ${{ secrets.ACCESS_SECRET }}
        run: python hello_world.py
